<a href="https://colab.research.google.com/github/kyalo-alfred/SemProject_MLEngine/blob/main/Dataset_Exploration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The first two cells are about cleaning the dataset to fit our requirements and saving that new dataset(modified)
Ignore it and skip to cell 3 first

In [ ]:
import pandas as pd

df = pd.read_csv('dataset.csv', keep_default_na=False, na_values=[''])

df_diab = df[df['Diabetes_Status'] == 1.0].drop(columns=['Diabetes_Status'])
df_clean = df_diab.dropna()


df_clean.to_csv('df_clean.csv', index=False)

In [ ]:
df_clean.shape
pd.set_option('display.max_columns', None)
df_clean

,Glucose,BMI,Insulin,Age,Gender,Diet_Type,Exercise_Frequency,Heredity,Smoking,Alcohol,Stress_Score,Sleep_Hours
0,101.3,30.9,83.6,51.0,Male,Healthy,3-5 times/week,No,No,None,7.5,6.5
1,121.8,28.0,78.7,52.0,Female,Unhealthy,Daily,No,No,Moderate,6.9,6.6
5,86.2,28.8,61.7,43.0,Female,Moderate,3-5 times/week,No,No,None,6.2,6.6
6,67.5,25.6,37.1,42.0,Male,Moderate,3-5 times/week,No,No,None,7.8,6.3
7,134.1,25.5,86.8,58.0,Male,Healthy,Daily,No,No,Low,5.7,7.7
...,...,...,...,...,...,...,...,...,...,...,...,...
4986,100.3,25.0,64.2,40.0,Male,Healthy,1-2 times/week,No,Yes,Moderate,10.0,6.3
4988,69.2,28.1,47.0,29.0,Male,Moderate,1-2 times/week,No,No,None,6.4,6.8
4989,125.4,25.9,77.2,59.0,Female,Healthy,3-5 times/week,Yes,No,Low,5.4,7.6
4994,140.1,28.8,83.6,46.0,Male,Unhealthy,Daily,Yes,No,None,3.8,6.8
4995,157.5,31.7,91.6,66.0,Male,Unhealthy,3-5 times/week,No,No,None,5.8,7.0

a

In [ ]:
df.shape

(5000, 13)

b

In [ ]:
df.dtypes

Glucose               float64
BMI                   float64
Insulin               float64
Age                   float64
Gender                 object
Diet_Type              object
Exercise_Frequency     object
Heredity               object
Smoking                object
Alcohol                object
Stress_Score          float64
Sleep_Hours           float64
Diabetes_Status       float64
dtype: object

 c- no the dataset is not complete, approximately 5% incompletion rate

In [ ]:
df.isnull().sum()

Glucose               249
BMI                   209
Insulin               256
Age                   241
Gender                246
Diet_Type             230
Exercise_Frequency    230
Heredity              257
Smoking               252
Alcohol               258
Stress_Score          252
Sleep_Hours           242
Diabetes_Status       240
dtype: int64

Column Diabetes status isn't the actual output and is irrellevant to our case, so after picking rows where diabetes status=1 the column will be dropped

d

In [ ]:
# raw
df_sample_raw = pd.concat([df.head(15), df.tail(20)])
df_sample_raw

,Glucose,BMI,Insulin,Age,Gender,Diet_Type,Exercise_Frequency,Heredity,Smoking,Alcohol,Stress_Score,Sleep_Hours,Diabetes_Status
0,101.3,30.9,83.6,51.0,Male,Healthy,3-5 times/week,No,No,None,7.5,6.5,1.0
1,121.8,28.0,78.7,52.0,Female,Unhealthy,Daily,No,No,Moderate,6.9,6.6,1.0
2,121.2,27.2,79.3,51.0,NaN,Healthy,3-5 times/week,No,No,Low,5.4,6.8,1.0
3,121.9,22.8,93.1,46.0,Male,Moderate,Daily,No,No,None,4.0,6.3,0.0
4,156.3,NaN,77.3,42.0,Male,Unhealthy,1-2 times/week,No,No,NaN,6.5,5.6,1.0
5,86.2,28.8,61.7,43.0,Female,Moderate,3-5 times/week,No,No,None,6.2,6.6,1.0
6,67.5,25.6,37.1,42.0,Male,Moderate,3-5 times/week,No,No,None,7.8,6.3,1.0
7,134.1,25.5,86.8,58.0,Male,Healthy,Daily,No,No,Low,5.7,7.7,1.0
8,113.4,20.8,72.5,52.0,Male,Unhealthy,Daily,No,No,Low,5.4,7.9,1.0
9,109.9,23.6,81.0,18.0,Female,Moderate,3-5 times/week,Yes,Yes,None,5.5,4.9,1.0
10,93.8,20.0,71.6,52.0,Male,Healthy,Rarely,Yes,No,None,4.2,7.2,1.0
11,144.5,18.2,89.4,47.0,Male,Moderate,Daily,No,No,None,8.9,7.5,0.0
12,116.4,28.4,68.6,44.0,Male,NaN,3-5 times/week,No,Yes,None,8.3,4.9,1.0
13,120.3,19.7,80.9,40.0,Male,Healthy,1-2 times/week,No,No,Low,3.6,7.2,1.0
14,148.3,28.5,107.2,58.0,Female,Healthy,Daily,Yes,No,Low,7.6,7.6,1.0
4980,153.4,27.2,103.3,60.0,Female,Unhealthy,3-5 times/week,No,No,Low,7.0,NaN,1.0
4981,85.5,19.5,56.1,56.0,Male,Moderate,1-2 times/week,No,No,Low,8.3,5.5,1.0
4982,151.9,29.2,122.0,23.0,Male,Moderate,1-2 times/week,NaN,No,NaN,1.5,6.9,1.0
4983,94.4,23.9,70.0,57.0,Female,Healthy,1-2 times/week,No,No,None,8.2,5.8,1.0
4984,63.7,31.3,53.5,22.0,NaN,Moderate,1-2 times/week,No,No,Low,2.6,NaN,1.0
4985,60.0,28.3,53.9,55.0,Male,Healthy,1-2 times/week,No,NaN,None,6.6,NaN,0.0
4986,100.3,25.0,64.2,40.0,Male,Healthy,1-2 times/week,No,Yes,Moderate,10.0,6.3,1.0
4987,122.5,31.5,71.5,53.0,Male,Moderate,1-2 times/week,No,NaN,None,5.9,6.1,1.0
4988,69.2,28.1,47.0,29.0,Male,Moderate,1-2 times/week,No,No,None,6.4,6.8,1.0
4989,125.4,25.9,77.2,59.0,Female,Healthy,3-5 times/week,Yes,No,Low,5.4,7.6,1.0
4990,115.4,28.6,83.3,27.0,Male,Moderate,3-5 times/week,No,Yes,Low,NaN,6.8,1.0
4991,122.3,34.8,77.4,NaN,Male,Unhealthy,1-2 times/week,Yes,No,None,6.7,6.3,1.0
4992,99.4,20.5,75.9,33.0,Female,NaN,3-5 times/week,Yes,No,None,4.6,7.3,1.0
4993,117.2,37.8,66.0,NaN,Male,Moderate,Rarely,No,Yes,None,5.8,7.5,NaN
4994,140.1,28.8,83.6,46.0,Male,Unhealthy,Daily,Yes,No,None,3.8,6.8,1.0
4995,157.5,31.7,91.6,66.0,Male,Unhealthy,3-5 times/week,No,No,None,5.8,7.0,1.0
4996,NaN,17.2,17.4,77.0,Female,Moderate,Rarely,No,No,Low,5.2,7.3,1.0
4997,113.4,26.6,72.1,46.0,Male,Moderate,NaN,NaN,Yes,Moderate,6.3,4.5,1.0
4998,71.8,26.9,45.5,58.0,Female,Healthy,Rarely,No,No,NaN,4.6,6.1,1.0
4999,126.1,20.3,87.6,47.0,Female,Moderate,Rarely,NaN,No,NaN,5.6,7.0,1.0

In [ ]:
# cleaned
df_sample_clean = pd.concat([df_clean.head(15), df_clean.tail(20)])
df_sample_clean

,Glucose,BMI,Insulin,Age,Gender,Diet_Type,Exercise_Frequency,Heredity,Smoking,Alcohol,Stress_Score,Sleep_Hours
0,101.3,30.9,83.6,51.0,Male,Healthy,3-5 times/week,No,No,None,7.5,6.5
1,121.8,28.0,78.7,52.0,Female,Unhealthy,Daily,No,No,Moderate,6.9,6.6
5,86.2,28.8,61.7,43.0,Female,Moderate,3-5 times/week,No,No,None,6.2,6.6
6,67.5,25.6,37.1,42.0,Male,Moderate,3-5 times/week,No,No,None,7.8,6.3
7,134.1,25.5,86.8,58.0,Male,Healthy,Daily,No,No,Low,5.7,7.7
8,113.4,20.8,72.5,52.0,Male,Unhealthy,Daily,No,No,Low,5.4,7.9
9,109.9,23.6,81.0,18.0,Female,Moderate,3-5 times/week,Yes,Yes,None,5.5,4.9
10,93.8,20.0,71.6,52.0,Male,Healthy,Rarely,Yes,No,None,4.2,7.2
13,120.3,19.7,80.9,40.0,Male,Healthy,1-2 times/week,No,No,Low,3.6,7.2
14,148.3,28.5,107.2,58.0,Female,Healthy,Daily,Yes,No,Low,7.6,7.6
15,108.7,31.2,64.5,56.0,Male,Healthy,1-2 times/week,No,No,None,2.3,5.4
18,91.0,31.2,50.2,33.0,Female,Moderate,3-5 times/week,Yes,Yes,None,6.7,7.2
19,100.9,32.3,70.4,28.0,Male,Unhealthy,3-5 times/week,No,No,None,2.1,5.3
21,136.8,20.6,84.7,55.0,Male,Moderate,1-2 times/week,Yes,Yes,None,6.9,4.1
22,95.8,24.7,72.5,56.0,Female,Healthy,1-2 times/week,No,No,Low,4.6,8.1
4957,148.5,37.2,90.9,44.0,Male,Unhealthy,Rarely,No,No,None,5.5,6.4
4959,97.8,25.0,59.9,37.0,Female,Healthy,1-2 times/week,No,No,Low,6.5,5.6
4960,174.4,25.3,111.1,50.0,Female,Unhealthy,3-5 times/week,Yes,No,None,7.1,6.4
4961,144.3,20.7,96.4,36.0,Male,Moderate,3-5 times/week,No,No,Low,4.9,7.8
4962,150.2,17.6,101.8,20.0,Female,Unhealthy,3-5 times/week,Yes,No,None,3.5,6.8
4965,106.0,29.6,79.1,31.0,Female,Healthy,3-5 times/week,Yes,No,None,7.5,5.1
4969,87.0,22.7,72.3,55.0,Female,Healthy,Rarely,No,Yes,Low,5.7,7.6
4971,106.9,24.8,66.8,44.0,Female,Healthy,Daily,No,No,Moderate,8.9,7.9
4972,116.5,23.4,101.1,55.0,Female,Moderate,3-5 times/week,Yes,No,Moderate,6.2,8.2
4976,112.1,24.0,71.9,39.0,Male,Moderate,3-5 times/week,No,No,None,6.3,5.7
4977,182.5,21.6,103.7,29.0,Male,Healthy,Daily,No,No,Low,5.7,5.1
4978,93.4,17.8,45.1,39.0,Female,Healthy,Rarely,No,No,Low,6.0,6.1
4979,101.5,28.5,74.7,56.0,Female,Healthy,3-5 times/week,No,No,Low,6.3,6.0
4981,85.5,19.5,56.1,56.0,Male,Moderate,1-2 times/week,No,No,Low,8.3,5.5
4983,94.4,23.9,70.0,57.0,Female,Healthy,1-2 times/week,No,No,None,8.2,5.8
4986,100.3,25.0,64.2,40.0,Male,Healthy,1-2 times/week,No,Yes,Moderate,10.0,6.3
4988,69.2,28.1,47.0,29.0,Male,Moderate,1-2 times/week,No,No,None,6.4,6.8
4989,125.4,25.9,77.2,59.0,Female,Healthy,3-5 times/week,Yes,No,Low,5.4,7.6
4994,140.1,28.8,83.6,46.0,Male,Unhealthy,Daily,Yes,No,None,3.8,6.8
4995,157.5,31.7,91.6,66.0,Male,Unhealthy,3-5 times/week,No,No,None,5.8,7.0